#!/usr/bin/env bash

set -euo pipefail

if [ -f ".remove" ]; then
	while IFS='' read -r filename; do
		if [ -e "${filename}" ]; then
			set -x
			rm -rf "${filename}"
			{ set +x; } 2> /dev/null
		fi
	done < ".remove"
fi
