@echo off

set "step="
set "step=%step% install/user"
set "step=%step% install/update"
set "step=%step% install/update-sid"
set "step=%step% install/locale"

set "step=%step% install/aria2c"
set "step=%step% install/curl"
set "step=%step% install/git"
set "step=%step% install/gnupg"
set "step=%step% install/jq"
set "step=%step% install/less"
set "step=%step% install/man"
set "step=%step% install/oathtool"
set "step=%step% install/patch"
set "step=%step% install/remove"
set "step=%step% install/ssh"
set "step=%step% install/vim"
set "step=%step% install/wget"
set "step=%step% install/xz"
