#!/usr/bin/env bash

set -euo pipefail

username=$(cat /etc/passwd | sed '/home/!d;s/:.*//')

echo "Restoring cache npm..."

su "${username}" <<-'EOF'
	set -euo pipefail

	'./cache-x' 'npm' "${HOME}"
EOF
