#!/usr/bin/env bash

set -euo pipefail

username=$(cat /etc/passwd | sed '/home/!d;s/:.*//')

echo "Restoring cache vscode server..."

su "${username}" <<-'EOF'
	set -euo pipefail

	'./cache-x' 'vscode-server' "${HOME}"
EOF
