#!/usr/bin/env bash

set -euo pipefail

username=$(cat /etc/passwd | sed '/home/!d;s/:.*//')
arch=$(dpkg --print-architecture)
codename=$(. /etc/os-release && echo "$VERSION_CODENAME")

echo "Installing docker..."

'./apt-get' -y install 'ca-certificates'

install -m 0755 -d '/etc/apt/keyrings'

curl -fsSL 'https://download.docker.com/linux/debian/gpg' -o '/etc/apt/keyrings/docker.asc'

chmod a+r '/etc/apt/keyrings/docker.asc'

cat <<-EOF > '/etc/apt/sources.list.d/docker.list'
	deb [arch=${arch} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian ${codename} stable
EOF

'./apt--get' update

'./apt-get' -y install 'docker-ce' 'docker-ce-cli' 'containerd.io' 'docker-buildx-plugin' 'docker-compose-plugin'

if [ ! -z "$(apt list --installed 2> /dev/null | grep 'git[/].*automatic')" ]; then
	'./apt-get' -y remove git
	'./apt-get' -y autopurge
fi

usermod -aG 'docker' "${username}"
